version: '3.3'
services:
  enigma:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8085:8085
    environment:
      - APP_ENV=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb/${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - app-network
    depends_on:
      mysqldb:
        condition: service_healthy
  mysqldb:
    image: mysql:9
    volumes:
      - mongo-data:/data/db
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - app-network
volumes:
  mongo-data:
    driver: local

networks:
  app-network:
    driver: bridge