version: '3.3'
services:
  db:
    image: mysql:9
    volumes:
      - mongo-data:/data/db
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
volumes:
  mongo-data:
    driver: local
